FORMAT: 1A
HOST: http://ir-carecenter.azurewebsites.net/api/

# Care Center API
Care Center is a simple API allowing consumers to search for non-profit organizations and services.

# Group Authentication
## OAuth Authentication
[NotImplemented] Currently the *Care Center API* does not provide OAuth 2 authenticated access.

<!--## Media Types-->
<!--Where applicable this API uses the [HAL+JSON](https://github.com/mikekelly/hal_specification/blob/master/hal_specification.md) media-type to represent resources states and affordances.-->


<!--Requests with a message-body are using plain JSON to set or update resource states.-->

## Error States
The common [HTTP Response Status Codes](https://github.com/for-GET/know-your-http-well/blob/master/status-codes.md) are used.

## Basic Access Authentication [/user]
[NotImplemented] Basic authentication using username and password.

### Login [GET]
+ Request (application/json)
    + Headers
    
            Location: /user

    + Attributes (UserRequest)
        
+ Response 200 (application/json)
    + Headers
    
            Location: /user
    
    + Attributes (UserResponse)

# Group Organizations
Organizations-related resources of *Care Center API*.

## Organizations Collection [/organizatons]

### View Organizations [GET]
Retrieve a list or single Organizations entities.

+ Request All Organizations (application/json)

+ Response 200 (application/json)

        [
            {
                "m_id": 1,
                "name": "Evanston Vineyard",
                "description": "Description about Evanston Vineyard",
                "created_at": "2015-08-05T08:40:51.620Z",
                "updated_at": "2015-08-05T08:40:51.620Z",
                "web_url": "http://www.evanstonvineyard.org",
                "enabled": true,
                "services": [
                    {
                        "name": "The Harvest",
                        "descripton": "Gently used clothing available Wednesdays 6-8pm",
                        "web_url": "http://www.evanstonvineyard.org/harvest",
                        "contact_email": "office@evanstonvineyard.org",
                        "contact_phone": "847-328-4544",
                        "street_address": "2495 Howard Street, Evanston, IL 60202",
                        "eligibility_desc": "Illinois residents",
                        "cost_desc": "No cost"
                    }
                ],
                "tags": [
                    "Food Distribution",
                    "Clothing Distribution"
                ]
            },
            {
                "m_id": 2,
                "name": "Evanston Police Department",
                "description": "Description about Evanston Police Department",
                "created_at": "2015-08-05T08:40:51.620Z",
                "updated_at": "2015-08-05T08:40:51.620Z",
                "web_url": "http://www.evanstonvineyard.org",
                "enabled": true,
                "services": [
                    {
                        "name": "Youth Services",
                        "descripton": "Provides Evanston youth and their families a broad range of social services including individual, family, and group counseling, crisis intervention, and street youth outreach intervention and prevention. Program also administers a community service program for youth offenders.",
                        "web_url": "",
                        "contact_email": "",
                        "contact_phone": "847-866-5000 or 311",
                        "street_address": "1454 Elmwood Ave, Evanston, IL 60201",
                        "eligibility_desc": "Youth ages 9-17 and their families",
                        "cost_desc": "No cost"                    
                    }, {
                        "name": "Victim Services",
                        "descripton": "Referrals or assistance obtaining Orders of Protection, court advocacy to assist victims and witnesses throught the criminal justice system, legal resoures and referrals regarding domestic violence and custody issues",
                        "web_url": "",
                        "contact_email": "",
                        "contact_phone": "847-866-5015",
                        "street_address": "1454 Elmwood Ave, Evanston, IL 60201",
                        "eligibility_desc": "Evanston individuals and families",
                        "cost_desc": "No cost"
                    }, {
                        "name": "Mentoring",
                        "descripton": "Administered by employees of the department who volunteer their efforts to support a better quality of life for youth. Mentoring is team-based and peer-based. Primary mentoring topics include dealing with authority, learning to effectively communicate, dealing with peer pressure, internet usage and social media responsibility, fear and respect, bullying, and many other topics. Mentoring meetings are held twice a month, one large group discussion meeting and one small team meeting/out/activity.",
                        "web_url": "",
                        "contact_email": "EPDmentoring@gmail.com",
                        "contact_phone": "847-866-5015",
                        "street_address": "1454 Elmwood Ave, Evanston, IL 60201",
                        "eligibility_desc": "Evanston school district 6th-12th grade students, at-risk and non at-risk",
                        "cost_desc": "No cost"
                    }
                ],
                "tags": [
                    "Adults Working with At-Risk Youth",
                    "Mentoring"
                ]
            },
            {
                "m_id": 3,
                "name": "Community and Economic Development Association of Cook County, Inc. (CEDA)",
                "description": "Description about CEDA",
                "created_at": "2015-08-05T08:40:51.620Z",
                "updated_at": "2015-08-05T08:40:51.620Z",
                "web_url": "http://www.cedaorg.net/",
                "enabled": true,
                "services": [
                    {
                        "name": "Low-income Housing",
                        "descripton": "CEDA works collectively with lenders to work out payment plans for those seeking mortgage delinquency assistance.  The Housing Program aworks with over 100 landlords throughout suburban Cook County to place extremely low income families in temporary and affordable housing.",
                        "web_url": "http://www.cedaorg.net/www2/HS.html",
                        "contact_email": "",
                        "contact_phone": "847-328-5166",
                        "street_address": "2010 Dewey Avenue, Lower Level",
                        "eligibility_desc": "Interested homeless families and individuals must be willing to move to west and northwest suburban Cook County and meet other program compliances.",
                        "cost_desc": "Fees upon request"
                    }, {
                        "name": "Transitional Housing for Homeless Individuals and Families",
                        "descripton": "CEDA Transitional Housing Program is designed to develop supportive housing and services that will allow homeless persons to live as independently as possible. The assistance of the supportive services is to help them to achieve residential stability, increase their skill and/or incomes, and obtain greater self-determination (i.e., more influences over decisions that affect their lives).",
                        "web_url": "http://www.cedaorg.net/www2/HS.html",
                        "contact_email": "",
                        "contact_phone": "847-328-5166",
                        "street_address": "2010 Dewey Avenue, Lower Level",
                        "eligibility_desc": "Interested homeless families and individuals must be willing to move to west and northwest suburban Cook County and meet other program compliances.",
                        "cost_desc": "Call for information"
                    }
                ],
                "tags": [
                    "Housing Assistance",
                    "youth-course"
                ]
            }
        ]

+ Request Single Organization (application/json)
    + Headers

            Location: /organization/2
            
+ Response 201 (application/json)
    + Headers

            Location: /organization/2

    + Attributes (OrganizationResponse)

### Create a New Organization [POST]
You may create your own organization using this action. It takes a JSON
object containing a organization and a collection of services in the
form of services offered.

+ Request (application/json)
    + Headers
    
            Location: /organization

    + Attributes (OrganizationRequest)

+ Response 201 (application/json)
    + Headers
    
            Location: /organizations/4

    + Attributes (OrganizationResponse)

### Update a Organization [PUT]
Perform an update on Organization entity. It takes a JSON
object containing a Organization.

+ Request (application/json)
    + Headers

            Location: /organization/2

    + Attributes (OrganizationRequest)
  
+ Response 201 (application/json)
    + Headers

            Location: /organization/2
    
    + Attributes (OrganizationResponse)

### Delete a Organization [DELETE]
Perform a delete on Organization entity.

+ Request (application/json)
    + Headers

            Location: /organization/2
            
+ Response 201 (application/json)
    + Headers
    
            Location: /organization/2
            
    + Attributes (MessageSuccessResponse)

# Group Services
Services-related resources of *Care Center API*.

## Services Collections [/services]

### View Services [GET]
Retrieve a list or single Services entities.

+ Request All Services (application/json)
    + Headers
            
            Location: /services

+ Response 200 (application/json)
    + Headers
            
            Location: /services

    + Attributes (array)
        + (ServiceResponse)
            + _id: 1 (number)
            + name: Clothes
        + (ServiceResponse)
            + _id: 2 (number)
            + name: Food Pantry
        + (ServiceResponse)
            + _id: 3 (number)
            + name: Bible Study
        + (ServiceResponse)
            + _id: 4 (number)
            + name: Youth Intervention
        + (ServiceResponse)
            + _id: 5 (number)
            + name: Young Mother Training
        + (ServiceResponse)
            + _id: 6 (number)
            + name: GED preparation
            
+ Request Single Service (application/json)
    + Headers

            Location: /services/2

    + Attributes (ServiceRequest)

+ Response 201 (application/json)
    + Headers

            Location: /services/2

    + Attributes (ServiceResponse)

### Create a New Services [POST]
You may create your own Services using this action. It takes a JSON
object containing a service.

+ Request (application/json)
    + Headers

            Location: /services

    + Attributes (ServiceRequest)

+ Response 201 (application/json)
    + Headers

            Location: /services/2

    + Attributes (ServiceResponse)
    

### Update a Services [PUT]
You may update Services using this action. It takes a id attribute of service object and attributes to update.

+ Request (application/json)
    + Headers

            Location: /services/2

    + Attributes (ServiceRequest)

+ Response 201 (application/json)
    + Headers

            Location: /services/2

    + Attributes (ServiceResponse)

### Delete a Services [DELETE]
You may delete Services using this action. It takes a id attribute of service object.

+ Request (application/json)
    + Headers

            Location: /services/2

    + Attributes (ServiceRequest)

+ Response 201 (application/json)
    + Headers

            Location: /services/2

    + Attributes (MessageSuccessResponse)
    
# Group Tags
Tags-related resources of *Care Center API*.


# Data Structures
## UserRequest (object)
+ username: jan_doe@mail.com (string, required)
+ password: thisP@ssw0rdWeak (string, required)

## UserResponse (object)
+ _id: 2 (number)
+ username: `jan_doe@mail.com` (string)
+ display_name: Jan Doe (string)
+ last_login: `2016-08-05T08:40:51.620Z` (string)

## RequestBase (object)
+ name: Care Center 501c3 (string, required)
+ description: Organization that cares. (string)
+ web_url: http://www.care.org (string)

## ResponseBase (object)
+ _id: 1001 (number)
+ created_at: `2015-08-05T08:40:51.620Z`
+ updated_at: `2015-08-05T08:40:51.620Z`
+ lat: `-74.016323` (number)
+ long: `40.710537` (number)

## OrganizationRequest (RequestBase)
+ name: Care Center 501c3 (string, required)
+ description: Organization that cares. (string)
+ web_url: http://www.care.org (string)
    
## OrganizationResponse (ResponseBase)
+ create_at: `2016-08-05T08:40:51.620Z` (string)
+ updated_at: `2016-08-05T08:40:51.620Z` (string)
+ services (array)
    + (ServiceResponse)
        + _id: 1 (number)
    + (ServiceResponse)
        + _id: 2 (number)
    + (ServiceResponse)
        + _id: 3 (number)

## ServiceResponseBase (object)
+ _id: 1001 (number)
+ created_at: `2015-08-05T08:40:51.620Z`
+ updated_at: `2015-08-05T08:40:51.620Z`
+ lat: `-74.016323` (number)
+ long: `40.710537` (number)

## ServiceRequest (RequestBase)
+ contact_email: email (string)
+ contact_phone: phone (string)
+ web_url: `http://www.evanstonvineyard.org/harvest` (string)
+ street_address: 1234 N. Somewhere (string)
+ eligibility_desc: 18+ (string)
+ cost_desc: No cost (string)

## ServiceResponse (ServiceResponseBase)
+ contact_email: email (string)
+ contact_phone: phone (string)
+ web_url: `http://www.evanstonvineyard.org/harvest` (string)
+ street_address: 1234 N. Somewhere (string)
+ eligibility_desc: 18+ (string)
+ cost_desc: No cost (string)

## MessageSuccessResponse (object)
+ messsage: success (string)

## MessageFailResponse (object)
+ message: fail (string)